
const BUTTON_DEFAULT_MSG = 'Click me';

const BUTTON_DEFAULT_PRIMARY_COLOR = '#8D8DDA';

const BUTTON_DEFAULT_SECONDARY_COLOR = '#ABD9D9';

export {
    BUTTON_DEFAULT_MSG,
    BUTTON_DEFAULT_PRIMARY_COLOR,
    BUTTON_DEFAULT_SECONDARY_COLOR
}