
const BUTTON_DEFAULT_MSG = 'Click me';

const DEFAULT_DIMENSION_VALUE = 'auto';

const DEFAULT_IMG_DIMENSION = '100px';

const BUTTON_DEFAULT_PRIMARY_COLOR = 'var(--app-primary-color)';

const BUTTON_DEFAULT_SECONDARY_COLOR = 'var(--app-secondary-color)';

const DEFAULT_PROFILE_IMG_PATH = 'src/resources/default.png';

export {
    BUTTON_DEFAULT_MSG,
    DEFAULT_DIMENSION_VALUE,
    DEFAULT_IMG_DIMENSION,
    BUTTON_DEFAULT_PRIMARY_COLOR,
    BUTTON_DEFAULT_SECONDARY_COLOR,
    DEFAULT_PROFILE_IMG_PATH
}