import './landing/LandingPage';
import './legal-docs/PrivacyPolicy';
import './legal-docs/LegalNotice';
import './legal-docs/TermsConditions';
import './sidebar/MainSidebar';
import './profile/ProfilePage';
import './search-results/SearchResults';
import './ranking/RankingPage';
import './update-password/UpdatePassword';