import './landing/LandingPage';
import './legal-docs/PrivacyPolicy';
import './legal-docs/LegalNotice';
import './legal-docs/TermsConditions';
import './sidebar/MainSidebar';
import './profile/ProfilePage';
import './update-password/UpdatePassword';
import './oauth-redirect/OAuthRedirect';
import './error-page/error-page';