name: ESLint

on:
  push:
    branches: [ "master", "betta" ]
  pull_request:
    branches: [ "master", "betta" ]

jobs:
  eslint:
    name: Run eslint scanning
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install and run ESLint
        run: |
          npm ci
          npm run lint
